mysql:
  host: 'localhost'
  port: 3306
  #База данных
  databases:
    dreamsait:
      user: ''
      password: ''

get-from:
  #Базы данных
  dreamsait:
    #Любое ебаное название....
    govnoedka:
      #SELECT `cost` FROM `dreamsait`.`AD_GOODS` WHERE `id`=1;
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '1'
    pizdabolka:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '2'
    chlennik:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '3'
    syka:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '4'
    ebal:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '5'
    rot:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '6'
    sex:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '7'
    elephant:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '8'
    kit:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '9'

#Ответы от запросов свыше
answers:
  govnoedka: '35'
  pizdabolka: '90'
  chlennik: '140'
  syka: '220'
  ebal: '299'
  rot: '570'
  sex: '840'
  elephant: '960'
  kit: '1200'