mysql:
  host: 'localhost'
  port: 3306
  #База данных
  databases:
    dreamsite:
      user: 'dreamsait'
      password: 'cZ$jaVoqslhI'

get-from:
  #Базы данных
  dreamsite:
    #Любое ебаное название....
    vip:
      #SELECT `cost` FROM `dreamsait`.`AD_GOODS` WHERE `id`=1;
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '1'
    iron:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '2'
    vipp:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '3'
    gold:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '4'
    mvp:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '5'
    ultra:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '6'
    mvpp:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '7'
    titan:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '8'
    godlike:
      table: 'AD_GOODS'
      select: 'cost'
      where-what: 'id'
      where-equals: '9'

#Ответы от запросов свыше
answers:
  vip: '35'
  iron: '90'
  vipp: '140'
  gold: '220'
  mvp: '299'
  ultra: '570'
  mvpp: '840'
  titan: '960'
  godlike: '1200'